
# -- (REQUIRED) Application name which will be used by all resources created via base chart. Also will be available via APPNAME variable inside pods
appName: "test-nginx"

image:
  # -- Repository applied to application deployment/statefulset
  repository: "nginx"
  # -- Tag applied to application deployment/statefulset
  tag: "1.14.2"
  # -- ImagePullPolicy applied to application deployment/statefulset
  imagePullPolicy: Always

# -- The number of application pods to run
replicas: 1

# -- Allows to define custom configMap objects with custom content
# -- Created configMaps can be used as a volume inside application pods (see `volumes` definition for examples)
configmapsMountPath: "/etc/kubernetes/configmaps"
configmaps:
  example-cm-1:
    kv_data:
      key-1: value-1
      key-2: value-2
    raw_data:
      somename: |
        line 1
        line 2
  example-cm-2:
    kv_data:
      key-3: value-3
      key-4: value-4
    raw_data:
      somename: |
        line 1
        line 2

# Use ArgoRollouts - https://github.com/argoproj/argo-rollouts
rollout:
  # -- Apply the strategy of the argo rollout
  strategy: {}
#    canary:
#      steps:
#        - setWeight: 20
#        - pause: {}
#    blueGreen:
#      autoPromotionEnabled: false
#      activeService: bluegreen-demo
#      previewService: bluegreen-demo-preview
# -- Use predefined rollout strategy. available values: "manual-canary-1-pod", "manual-canary-20-pct"
  preDefinedStrategy: ""

# -- Variables of the configmap-attacher
configmapAttacher:
  repository: "quay.io/liorfranko/configmap-attacher"
  tag: 1.0.1
  resources:
    limits:
      cpu: 0.1
      memory: 100Mi
    requests:
      cpu: 0.1
      memory: 100Mi
