
# -- Application name which will be used by all resources created via base chart.
appName: "test-service"
kubeTargetVersionOverride: ""

image:
  # -- Repository applied to application
  repository: "nginx"
  # -- Tag applied to application
  tag: "1.14.1"
  # -- ImagePullPolicy applied to application
  imagePullPolicy: Always

# -- The number of application pods to run
replicas: 1

# -- Allows to define custom configMap objects with custom content
configmapsMountPath: "/etc/kubernetes/configmaps"
configmaps:
  example-cm-1:
    kv_data:
      key-1: value-13
      key-2: value-2
    raw_data:
      somename: |
        line 1
        line 2
  example-cm-2:
    kv_data:
      key-3: value-3
      key-4: value-4ss
    raw_data:
      somename: |
        line 1
        line 2

# ArgoRollouts - https://github.com/argoproj/argo-rollouts
rollout:
  # -- Use custom strategy of the argo rollout
  strategy: {}
#    canary:
#      steps:
#        - setWeight: 20
#        - pause: {}
# -- Use predefined rollout strategy. available values: "manual-canary-1-pod", "manual-canary-20-pct"
  preDefinedStrategy: "manual-canary-1-pod"

# -- Variables of the configmap-attacher
configmapAttacher:
  repository: "quay.io/liorfranko/configmap-attacher"
  tag: 1.0.3
  resources:
    limits:
      cpu: 0.1
      memory: 100Mi
    requests:
      cpu: 0.1
      memory: 100Mi

rbac:
  enabled: true
