appName: test-consumer
project: test-project
owner: general
team: devops
environment: dev
clusterNum: "01"
image:
  repository: 032106861074.dkr.ecr.us-east-1.amazonaws.com/some-repo
  tag: latest
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 1
    memory: 1024Mi
service:
  enabled: false
configmaps:
  first-configmap:
    raw_data:
      developments.json: |
        {
          "general": {
            "projectName": "helm-base-app",
          }
        }
